### ISSUE TITLE
The plugin `adtrace_sdk` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by sajjadG** [adtrace/adtrace_sdk_flutter#1]
I'm following the readme and adding `adtrace_sdk: ^0.1.3` to my `pubspec.yaml`, it show's this error:

```
$ flutter packages get
Running "flutter pub get" in Befarman-Flutter...                 1,400ms
The plugin `adtrace_sdk` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter
will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

pubspec.yaml:
```
...
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
...
```
